services:
  book:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: mlintro-book
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3000:3000"
    volumes:
      - .:/book
    environment:
      - HOST=0.0.0.0
    command: jupyter-book start --port 3000 --keep-host
